- hosts: all
  name: Autoconverted job legacy-karbor-dsvm-fullstack from old job gate-karbor-dsvm-fullstack-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              https://opendev.org \
              openstack/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[post-config|$SWIFT_CONFIG_PROXY_SERVER]]
          [DEFAULT]
          workers=4

          [[post-config|$CINDER_CONF]]
          [DEFAULT]
          osapi_volume_workers=8
          rpc_response_timeout=120

          [[post-config|$KARBOR_API_CONF]]
          [DEFAULT]
          max_window_time=150
          min_window_time=75
          min_interval=300

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_INSTALL_TESTONLY=1


          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          export PROJECTS="openstack/karbor $PROJECTS"
          export PROJECTS="openstack/trove $PROJECTS"
          export PROJECTS="openstack/trove-dashboard $PROJECTS"
          export PROJECTS="openstack/manila-tempest-plugin $PROJECTS"
          export DEVSTACK_PROJECT_FROM_GIT="python-karborclient"

          export DEVSTACK_GATE_SETTINGS=/opt/stack/new/karbor/devstack/devstackgaterc

          function gate_hook {
              bash -xe $BASE/new/karbor/karbor/tests/contrib/gate_hook.sh fullstack
          }
          export -f gate_hook

          function post_test_hook {
              bash -xe $BASE/new/karbor/karbor/tests/contrib/post_test_hook.sh fullstack
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
